name: CI Builds

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore CreamInstaller.sln

      - name: Build Release
        run: dotnet build CreamInstaller.sln --configuration Release --no-restore

      - name: Publish single-file
        run: dotnet publish CreamInstaller.sln -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true --output ./publish

      - name: Set short commit SHA
        id: vars
        run: |
          $shortSha = $env:GITHUB_SHA.Substring(0,7)
          Write-Output "shortSha=$shortSha" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Rename EXE with short commit SHA
        run: |
          Rename-Item -Path ./publish/CreamInstaller.exe -NewName "CreamInstaller-CI-$env:shortSha.exe"
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: CreamInstaller-CI-Release-${{ env.shortSha }}
          path: ./publish/CreamInstaller-CI-${{ env.shortSha }}.exe
